export const courseCopy = {
  ar: {
    courses: "دوراتي",
    coursePath: "مسار التعلم",
    overview: "اختر مسارًا يناسب مستواك وواصل تقدمك خطوة بخطوة.",
    dashboard: "لوحة التحكم",
    homework: "واجباتي",
    level: "المستوى",
    progress: "التقدم",
    lessons: "دروس",
    lesson: "الدرس",
    completed: "مكتمل",
    incomplete: "غير مكتمل",
    completeLesson: "إكمال الدرس",
    openLesson: "فتح الدرس",
    completing: "جارٍ الحفظ...",
    completedLesson: "تم إكمال الدرس",
    locked: "مقفل",
    available: "متاح الآن",
    comingSoon: "قريبًا",
    futureTitle: "برامج قادمة",
    futureDescription: "ستتوفر هذه البرامج عند إطلاق المرحلة التالية من المنصة.",
    noCourses: "لا توجد دورات متاحة حاليًا.",
    signIn: "سجّل الدخول لعرض دوراتك",
    loading: "جارٍ تحميل الدورات...",
    errorTitle: "تعذر تحميل الدورات",
    retry: "إعادة المحاولة",
    back: "العودة إلى دوراتي",
    noLessons: "لا توجد دروس منشورة في هذه الدورة بعد.",
    restricted: "هذه الدورة غير متاحة لمستواك الحالي.",
    courseDetails: "تفاصيل الدورة",
    learningMaterial: "محتوى الدرس",
    language: "English",
    home: "الرئيسية",
  },
  en: {
    courses: "My Courses",
    coursePath: "Learning path",
    overview: "Choose a path for your level and keep moving forward, one lesson at a time.",
    dashboard: "Dashboard",
    homework: "Homework",
    level: "Level",
    progress: "Progress",
    lessons: "lessons",
    lesson: "Lesson",
    completed: "Completed",
    incomplete: "Incomplete",
    completeLesson: "Complete lesson",
    openLesson: "Open lesson",
    completing: "Saving...",
    completedLesson: "Lesson completed",
    locked: "Locked",
    available: "Available now",
    comingSoon: "Coming soon",
    futureTitle: "Future programs",
    futureDescription: "These programs will become available in the next stage of the platform.",
    noCourses: "No courses are available yet.",
    signIn: "Sign in to view your courses",
    loading: "Loading courses...",
    errorTitle: "Could not load courses",
    retry: "Try again",
    back: "Back to my courses",
    noLessons: "No lessons have been published in this course yet.",
    restricted: "This course is not available for your current level.",
    courseDetails: "Course details",
    learningMaterial: "Lesson material",
    language: "العربية",
    home: "Home",
  },
};

export function localizedCourse(course, language) {
  return {
    ...course,
    displayTitle: language === "ar" ? course.titleAr : course.title,
    displayDescription: language === "ar" ? course.descriptionAr : course.description,
  };
}

export function formatProgress(progress) {
  return progress?.percentage || 0;
}
